Added customerBillId to databases
cgerard321/champlain_petclinic pull request #108
Opened 2021-10-01 19:25 UTC by jumpung

In this pull request I added customerBillId to everything that needed it

2021-10-01 23:28 UTC, Trim0500 requested changes
Can't accept this right now

Jira:

![image](https://user-images.githubusercontent.com/70395022/135695529-14e8f7cf-d83d-4854-aa28-faa45097059b.png)

There is no user story put in, I don't know what this story is supposed to accomplish. There are no subtasks defined either. We can't know what the status of the story is.

The PR naming convention isn't followed, remember the format is feat(TEAMTAG-CPC-###): Desc

Lastly and credit to Justin, but the customerBillId should be a foreign key if we are to use Auth service's sessions

2021-10-04 20:18 UTC, Trim0500 commented on billing-service/src/main/java/com/petclinic/billing/datalayer/Bill.java
> +    //int customerId ---> Add this to constructor maybe?
I think we can remove the comment out here and implement the field your considering. Do you agree?

2021-10-05 00:36 UTC, LemireCoding approved these changes
Comments were removed like asked. Good and ready to merge

2021-10-05 00:57 UTC, Trim0500 approved these changes
All changes have been addressed, I approve this message!

2021-10-05 01:04 UTC, LemireCoding approved these changes
Comments were removed. Everything looks good to go

2021-10-05 01:12 UTC, merged