feat(VETS-CPC-90): Added backend data validation method to filter out bad inputs
cgerard321/champlain_petclinic pull request #37
Opened 2021-09-24 21:16 UTC by Louenes099

Testing has also been added to test bad data.
Everything works.

2021-09-24 22:02 UTC, SmoothWin requested changes
All is good but test display names are too long. Display Names should be shorter and method names should not be should<something...something> but just be a short description of the method itself: for example method name and display for "shouldRegisterTheDataByFilteringOutTheTypos()" should instead be 
VetRegisterDataFilterAndValidationTest
and for the display name it should be no what it will do it should just be similar to the method name such as:
"Vet input submission cleanup and validation Test"
Change these method names and display names and I will accept the pull request

2021-09-24 23:41 UTC, amine-12 submitted a review, later dismissed

2021-09-25 00:36 UTC, SmoothWin requested changes
And remove the system.out.println in line 70 and 102 inside the VetResourceTest.java file

2021-09-25 22:32 UTC, SmoothWin approved these changes
Changes are satisfactory the printlns are removed and display names modified/ added

2021-09-25 22:43 UTC, closed without merging

2021-09-25 23:43 UTC, amine-12 approved these changes