feat(VETS-CPC-744): Update rating for vet by vetId and ratingId implemented
cgerard321/champlain_petclinic pull request #416
Opened 2023-09-21 19:45 UTC by DRMADNESS2004

Update rating for vet by vetId and ratingId implemented

JIRA: link to jira ticket
CPC-744
https://champlainsaintlambert.atlassian.net/browse/CPC-744

## Context:
This ticket implements the update rating of a vet by vetId and ratingId in the vet-service and api-gateway. The user is now able to edit their ratings if they want to go back on them. Although they aren't able to see the rating description they added yet, it will be displayed in the near future. 

## Changes
- The "updateRatingByVetIdAndByRatingId" method was implemented in VetsServiceClient, BFFApiGatewayController, VetController, RatingService, and RatingServiceImpl.
- The "vet-details.component.js" has been updated to be able to update an existing rating with its ratingId and rating data from the update form fields.
- The "vet-details.template.html" has been updated to have a button "Edit" at the bottom of each rating. After being clicked, the form to update the rating is displayed and the button text becomes "Save". After the button was clicked again, the form is hidden, the button text changes back to "Edit" and the new rating score is displayed.
- The Rating Repository has been tested.
- The Rating Service Impl has been tested (100%).
- The "updateRatingByVetIdAndByRatingId" method has been tested (100%) in the controller integration test.
- The "updateRatingByVetIdAndByRatingId" method has been tested in the api-gateway added.
- The "handleNotFoundException" method was added in the GlobalControllerExceptionHandler.

## Before 
![image](https://github.com/cgerard321/champlain_petclinic/assets/80173588/1409b25f-c5f8-4073-badd-28a41aea686c)

## After
![image](https://github.com/cgerard321/champlain_petclinic/assets/80173588/55dd50aa-aa23-49e0-bd84-2d1cfe43275d)

## Dev notes (Optional)
- Specific technical changes that should be noted
## Linked pull requests (Optional)
- pull request link

2023-09-21 23:44 UTC, Mila5847 approved these changes
The logic for updating the rating looks good. Exceptions were handled (not found and invalid input), tests were done and front-end is updated.

2023-09-22 01:05 UTC, Sprytte requested changes
Everything looks good, the back-end seems well-implemented as well as the front-end. The criteria are met and the tests are well implemented with 90% coverage, except for the repository test that seems to be missing the act and assert

2023-09-22 02:10 UTC, Sprytte approved these changes
Everything looks good and fixed!

2023-09-22 02:19 UTC, Mila5847 approved these changes
Repo tests were updated to include description and date.

2023-09-22 02:23 UTC, merged