feat(CART-1044): See users' carts with a dynamic user interface
cgerard321/champlain_petclinic pull request #713
Opened 2024-09-21 02:22 UTC by AlexCristea04

**JIRA:** link to jira ticket
## Context:
This ticket adds react pages for the user carts and the list of all carts. Additionally, I have added API gateway implementation, as our endpoints were not working before, therefore I could not tie the frontend to the backend. Get all has been implemented, and all carts are displayed using it.

## Does this PR change the .vscode folder in petclinic-frontend?:
No.

## Changes
- Added API gateway implementation (service client, controller, DTOs)
- Added UserCart, CartTable, CartItem react components, along with their individual CSS files
- Fetched the carts within CartTable using get all 
- Created the cart page, modified the nav bar
- Added routing 

## Before and After UI (Required for UI-impacting PRs)
![{A33BC9E9-DDEB-4EC1-8C68-40789E5A8B70}](https://github.com/user-attachments/assets/4db4808f-e199-45d5-96f9-e73f93deb3de)
![{D202EB85-B27F-4224-B26A-C722E4D3CE7E}](https://github.com/user-attachments/assets/4c3e3d72-d97c-4bbc-9a2f-5985d2e26111)

2024-09-21 02:30 UTC, FelixAllard commented on petclinic-frontend/src/features/carts/components/CartItem.tsx
> +export default CartItem;
What..???? The export statement is there so i don't understand all the conflicts... Also the code seems to be working on my end...

2024-09-21 02:32 UTC, FelixAllard commented on petclinic-frontend/src/router.tsx
EXTRA IMPORT NOT NEEDED! This can cause issue... Fix this!

2024-09-21 02:34 UTC, FelixAllard requested changes
Please update upon my comments!

2024-09-21 02:43 UTC, FelixAllard submitted a review, later dismissed
There is some fail in the Gateway and in Vet. Those error seems to have been imported from main and as such are not created by this commit. As such, with the correction you did, looks good to me!

2024-09-21 03:07 UTC, NtsoaElie submitted a review, later dismissed
Everything looks fine to me.

2024-09-21 23:51 UTC, NtsoaElie submitted a review, later dismissed

2024-09-22 14:49 UTC, NtsoaElie submitted a review, later dismissed

2024-09-22 19:27 UTC, NtsoaElie reviewed
Changed everything we reviewed on previously and fixed the CI checks.

2024-09-22 20:38 UTC, PaoloOabel approved these changes
The new UI looks really good!

2024-09-22 20:40 UTC, NtsoaElie approved these changes
Changed everything as commented before.

2024-09-22 20:41 UTC, merged