feat(APIG-CPC 48): Get billing info by ID
cgerard321/champlain_petclinic pull request #74
Opened 2021-09-27 02:58 UTC by Ludo67

2021-09-27 13:11 UTC, VladPopa616 requested changes
The reason your build fails is that you have a @NoArgConstructor annotation. Remove that and try again.

2021-09-27 13:15 UTC, Ludo67 commented
Will do asap

2021-09-27 13:34 UTC, Ludo67 commented
Screwed up the merge conflict sorry. Will do it as soon as I get home

2021-10-11 23:25 UTC, LawrenceLiang02 commented on api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java
> +        assertEquals(entity.getBillId(), 1);
This is questionable, you are just getting what you have set and comparing it but ok.

2021-10-11 23:27 UTC, LawrenceLiang02 commented on api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java
> +    void getBillingByRequestMissingPath(){
Do you think the tests should start with "should" as explained in class?

2021-10-11 23:35 UTC, VladPopa616 approved these changes
Some formatting issues, but I will approve it.

2021-10-11 23:35 UTC, VladPopa616 commented on api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/BillServiceClient.java
> +
This seems fine.

2021-10-11 23:35 UTC, VladPopa616 commented on api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/BillDetails.java
> +}
DTO class, nothing to say here.

2021-10-11 23:35 UTC, VladPopa616 commented on api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java
> +
Watch the spacing

2021-10-11 23:35 UTC, VladPopa616 commented on api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java
> +
GetMapping seems good here

2021-10-11 23:35 UTC, VladPopa616 commented on api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java
> +                                .map(addVisitsToOwner(owner)));
So what exactly was the change here? I'm assuming indents?

2021-10-11 23:35 UTC, VladPopa616 commented on api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java
> +
Big empty space.

2021-10-11 23:35 UTC, VladPopa616 commented on api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java
> +    public void getBillById(){
Remember Jason's naming convention for tests it should start with "should" or "test" or something like that. Applies to all tests.

2021-10-11 23:35 UTC, VladPopa616 commented on api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java
> +
Overall good test.

2021-10-11 23:35 UTC, VladPopa616 commented on api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java
> +
Good error case tests.

2021-10-11 23:50 UTC, merged