Feat/cart cpc 1255 create a whishlist
cgerard321/champlain_petclinic pull request #798
Opened 2024-09-30 01:58 UTC by Hares-2088

**JIRA:** [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1256)
## Context:
I changed the way we get the products and how we handle them in the cart. instead of a list of ids, we now have products stored in the carts
## Does this PR change the .vscode folder in petclinic-frontend?:
no, it doesn't
<span style="color:red">**Reviewers need to check for any changes to the 
.vscode folder and add a comment about it to their review comments.**</span>

## Changes
- I changed the entity so therefore almost every other class so that the requests work.
- Someone commented on some lines of codes in the front end so I put them back
- I commented on many tests for now. I'm going to write them again. i did it so that my teammates could work on their part

2024-09-30 21:45 UTC, AlexCristea04 requested changes
Please revise the commented tests in CartServiceUnitTest

2024-09-30 21:45 UTC, AlexCristea04 commented on cart-service/src/test/java/com/petclinic/cartsservice/businesslayer/CartServiceUnitTest.java
A lot of these tests shouldn't be commented out. Please revise.

2024-09-30 22:14 UTC, Hares-2088 commented on cart-service/src/test/java/com/petclinic/cartsservice/businesslayer/CartServiceUnitTest.java
I forgot to put them back. thank you for bringing it to my attention. it is fixed

2024-09-30 23:02 UTC, AlexCristea04 submitted a review, later dismissed
Works fine on my machine and changes were made according to my requests!

2024-10-01 01:39 UTC, NtsoaElie approved these changes
Implements everything as we discussed during our Sprint Planning and brainstorming. Good job!

2024-10-01 01:48 UTC, AlexCristea04 approved these changes
Minor changes since my last approval. Everything looks good

2024-10-01 01:52 UTC, merged