feat(CART-CPC-1341) : Add Image To Cart Product
cgerard321/champlain_petclinic pull request #971
Opened 2024-10-18 18:21 UTC by NtsoaElie

**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1341
## Context:
This aims to implement the feature of being able to see an image next to the user cart in product.
## Does this PR change the .vscode folder in petclinic-frontend?: No

<span style="color:red">**Reviewers need to check for any changes to the 
.vscode folder and add a comment about it to their review comments.**</span>

## Changes
- Added imageId in the ProductResponseModel in both backend and frontend
- Added GetImage API call in the frontend
- Added ImageContainer Component in the frontend
## Before and After UI (Required for UI-impacting PRs)
BEFORE: 
![image](https://github.com/user-attachments/assets/2a8d7983-b367-4f81-918c-11a711689ab8)

AFTER: 
![image](https://github.com/user-attachments/assets/92654173-8421-4a1d-8c7d-02359cf789b3)

2024-10-19 23:07 UTC, AlexCristea04 commented on petclinic-frontend/src/features/carts/components/ImageContainer.tsx
redundant class. you can just import the existing imagecontainer found in the products components. please fix this in your next pull request.

2024-10-19 23:41 UTC, AlexCristea04 commented on petclinic-frontend/src/features/carts/components/UserCart.tsx
overrides multiple features that are currently in main. a dysfunctional remove button in wishlist is added for some reason? checkout is working like the old version in sprint 2 instead of the current one. format of the cart is changed too. please fix.

2024-10-19 23:42 UTC, AlexCristea04 requested changes
please review my comments

2024-10-20 21:37 UTC, NtsoaElie commented on petclinic-frontend/src/features/carts/components/ImageContainer.tsx
I fixed it.

2024-10-20 22:07 UTC, AlexCristea04 approved these changes
Changes done according to previous comments. Nice work!

2024-10-20 22:08 UTC, NtsoaElie commented on petclinic-frontend/src/features/carts/components/UserCart.tsx
Okay, I will fix it

2024-10-20 22:12 UTC, Hares-2088 approved these changes
You fixed all the issues and everything works fine

2024-10-20 22:12 UTC, merged